name: Inmobiliaria Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Instalar Google Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Instalar dependencias de Python
        run: pip install -r requirements.txt
      - name: Ejecutar el Scraper con Selenium
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python scraper_aedas.py
