# Nombre del workflow que aparece en la pestaña "Actions" de GitHub
name: AEDAS SCRAPER

# Controla cuándo se ejecuta el workflow
on:
  # Permite ejecutarlo manualmente desde la pestaña Actions
  workflow_dispatch:
  # Lo ejecuta automáticamente a una hora programada (ej: todos los días a las 8 AM UTC)
  schedule:
    - cron: '0 8 * * *'

# Define los trabajos que se van a ejecutar
jobs:
  build:
    # El tipo de máquina virtual donde se ejecutará
    runs-on: ubuntu-latest

    steps:
      # 1. Clona tu repositorio para que el workflow tenga acceso a tus archivos
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura el entorno de Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Usa la versión de Python que prefieras

      # 3. ¡ESTE ES EL PASO QUE FALTABA!
      #    Instala las dependencias listadas en tu archivo requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. Ejecuta tu script de Python
      - name: Ejecutar scraper
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python scraper_aedas.py
