name: AEDAS Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '15 6 * * *'  # 08:15 CET

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_CHAT_ID:  ${{ secrets.TG_CHAT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper_aedas.py

      - name: Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: promociones_aedas
          path: promociones_aedas.csv
