name: Inmobiliaria Scraper

on:
  # ▶ permite lanzarlo a mano desde la pestaña “Actions”
  workflow_dispatch:

  # ▶ ejecución automática cada día a las 08:00 en España (06 UTC)
  schedule:
    - cron: '0 6 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # 1 ▸ clona tu repositorio
      - uses: actions/checkout@v4

      # 2 ▸ configura Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3 ▸ cachea los paquetes de pip (acelera las siguientes ejecuciones)
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      # 4 ▸ instala dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5 ▸ ejecuta el orquestador y envía el mensaje a Telegram
      - name: Run scrapers and notify
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python run_scrapers.py